### ISSUE TITLE
Add info on how R in 3 works

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/rin3-info-session#1]
@graciellehigino please add this info the slides.qmd file.

**Comment by graciellehigino** [comment]
Ugh forgot to mention this issue in the commit message!

Adding it here for the record:

[c932410](https://github.com/rfortherestofus/rin3-info-session/commit/c9324101ebf55c340b00eb9a212c0aa21bb4c08d)

**Comment by dgkeyes** [comment]
Awesome, thanks!
